#!/bin/bash
cd && cd menu && sudo net-path-iperf-test.sh --auto
if sudo ethtool -S enp3s0 | grep -E 'rx_crc_errors: 0'; then
    echo OK
else
    sudo ethtool -S enp3s0 | grep -E 'rx_crc_errors:' 
    read
fi
