#!/bin/bash
sudo ip addr add 172.30.134.100/24 dev enp3s0 
iperf3 -c 172.30.134.8 -n 50G || read
# iperf3 -c 172.30.134.8 || read
if sudo ethtool -S enp3s0 | grep -E 'rx_crc_errors: 0'; then
    echo OK
else
    sudo ethtool -S enp3s0 | grep -E 'rx_crc_errors:' 
    read
fi
